# Site settings
title: Andrew Maudsley
email: andrew@andrewmaudsley.com
description: > # this means to ignore newlines until "baseurl:"
  Independent software developer and consultant
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewmaudsley.com" # the base hostname & protocol for your site
twitter_username: ndrewmaudsley
github_username:  andrewmaudsley
linkedin_username: andrewmaudsley	



# Build settings
markdown: kramdown
exclude: [CNAME, Gemfile, Gemfile.lock, README.md, _sass]
